- Exception handling là xử lý các trường hợp ngoại lệ, ví dụ như trong lệnh `try/except` hay dùng.
# Các loại lỗi hay gặp
1. Common Exceptions: một số exception đã được định nghĩa sẵn trong python như:
  - Exception (this is what almost all the others are built off of)
  - AttributeError - Xảy ra khi không gán hoặc tham chiếu biến thành công
  - IOError -chẳng hạn lệnh print, phương thức open hoặc các phương thức khác) không thành công
    vì những lí do chẳng hạn như không tìm thấy file hoặc ổ đĩa đầy 
  - ImportError - Xảy ra khi lệnh import không thành công trong việc tìm midule hoặc không tìm thấy file chứa module cần import 
  - IndexError - Xảy ra khi 1 tập biến bị quá giới hạn.
  - KeyError - Xảy ra khi key của dictionary không mapping được sang values.
  - KeyboardInterrupt - Xảy ra khi người dung nhấn Ctrl-C (normally Control-C or Delete).
  - NameError - Xảy ra khi 1 tên của biến không được tìm thấy
  - OSError - Xảy ra khi hàm trả về một lỗi liên quan đến hệ thống.
  - SyntaxError - Lỗi cú pháp
  - ValueError - Xảy ra khi kiểu của đối tượng không phù hợp với function hoặc câu lệnh mình bắt nó chạy cùng
  - ZeroDivisionError - khi số chia bằng 0
  
  # Sử dụng Try và Exception
  ```
  try:
        1 / 0
  except ZeroDivisionError:
        print("You cannot divide by zero!")
  ```
  
  Ngoài ra còn có thêm cả quả finally
   ```
  try:
        1 / 0
  except ZeroDivisionError:
        print("You cannot divide by zero!")
  finally:
    print("Oke")
  
  ```
  dù có lỗi hay không có lỗi thì vẫn sẽ chạy finally
  Tiếp theo là quả else
   ```
  try:
        1 / 0
  except ZeroDivisionError:
        print("You cannot divide by zero!")
  else:
      print("Không gặp lỗi")
      
  ```
  Nếu ko có lỗi thì nó sẽ chạy vào cái else và đằng sau nó có finally thì nó vẫn sẽ chạy vào finally
        
        
        
        
        
        
        
